baseURL = 'https://zedcole.github.io'
languageCode = 'en-au'
title = 'Zed Cole'
theme = 'zedcole'

sectionPagesMenu = 'main'

[params]

[[params.socialLinks]]
title = "Github"
url = "https://github.com/zedcole"

[[params.socialLinks]]
title = "Email"
url = "mailto:zed@zedcole.com"
