baseURL = 'https://zedcole.github.io'
languageCode = 'en-au'
title = 'Zed Cole'
theme = 'zedcole'

[menu]
[[menu.main]]
    pageRef = "/"
    name = 'Home'
    url = '/'
    weight = 10
[[menu.main]]
    pageRef = "posts"
    name = 'Posts'
    url = '/posts'
    weight = 20

[params]
[[params.socialLinks]]
title = "Github"
url = "https://github.com/zedcole"

[[params.socialLinks]]
title = "Email"
url = "mailto:zed@zedcole.com"
